\begin{table}[!ht]
\caption{Vaccine effectiveness and protection provided by post-infection immunity against hospitalization with a {\it need for oxygen therapy}, for the Omicron and Delta variants of the SARS-CoV-2 virus, 95\% confidence intervals (CI) in parentheses.}
\vspace{2mm}
\label{tabOalone}
\centering
\begin{tabular}{|l|c|c|}
\hline
\cellcolor{gray!20}Effect ag. $O_2$&\cellcolor{gray!20}Omicron&\cellcolor{gray!20}Delta\\
\hline
Full 2-& 57\% (32-72\%) & 82\% (76-87\%)\\
\cellcolor{gray!10}Full 2+& \cellcolor{gray!10}32\% (20-43\%)&\cellcolor{gray!10}82\% (80-83\%)\\
Booster 2-&90\% (87-92\%)&98\% (98-98\%)\\
\cellcolor{gray!10}Booster 2+&\cellcolor{gray!10}85\% (80-88\%)&\cellcolor{gray!10}97\% (95-98\%)\\
Inf 6-& 81\% (40-94\%)&100\% (no case)\\
\cellcolor{gray!10}Inf 6+&\cellcolor{gray!10}88\% (72-94\%)&\cellcolor{gray!10}98\% (95-99\%)\\
\hline
\end{tabular}
\end{table}

