\begin{table}[!ht]
\caption{Vaccine effectiveness and protection provided by post-infection immunity {\it against hospitalization}, for the Omicron and Delta variants of the SARS-CoV-2 virus, 95\% confidence intervals (CI) in parentheses.}
\vspace{2mm}
\label{tabHalone}
\centering
\begin{tabular}{|l|c|c|}
\hline
\cellcolor{gray!20}Effect ag. {\it Hosp.} & \cellcolor{gray!20} Omicron & \cellcolor{gray!20} Delta \\
\hline
Full 2-&45\% (29-57\%)&73\% (69-76\%)\\
\cellcolor{gray!10}Full 2+&\cellcolor{gray!10}29\% (21-37\%) &\cellcolor{gray!10}77\% (76-79\%)\\
Booster 2-&86\% (84-88\%)&97\% (97-98\%)\\
\cellcolor{gray!10}Booster 2+&\cellcolor{gray!10}79\% (75-82\%)&\cellcolor{gray!10}96\% (94-97\%)\\
Inf 6-& 
73\% (55-84\%)
&100\% (\nocase)\\
\cellcolor{gray!10}Inf 6+&\cellcolor{gray!10}
66\% (54-75\%) 
&\cellcolor{gray!10}94\% (91-96\%)\\
\hline
\end{tabular}
\end{table}


