\begin{table}[!ht]
\caption{Vaccine effectiveness and protection provided by post-infection immunity against hospitalization with a need for {\it intensive care}, for the Omicron and Delta variants of the SARS-CoV-2 virus, 95\% confidence intervals (CI) in parentheses.}
\vspace{2mm}
\label{tabUalone}
\centering
\begin{tabular}{|l|c|c|}
\hline
\cellcolor{gray!20}Effect ag. {\it ICU}&\cellcolor{gray!20}Omicron&\cellcolor{gray!20}Delta\\
\hline
Full 2-&58\% (3-82\%)&84\% (72-91\%)\\
\cellcolor{gray!10}Full 2+&\cellcolor{gray!10}37\% (12-55\%)&\cellcolor{gray!10}86\% (83-88\%)\\
Booster 2-&83\% (75-89\%)&98\% (97-99\%)\\
\cellcolor{gray!10}Booster 2+&\cellcolor{gray!10}60\% (37-74\%)&\cellcolor{gray!10}97\% (92-99\%)\\
Inf 6-&83\% (0-98\%)&100\% (no case)\\
\cellcolor{gray!10}Inf 6+&\cellcolor{gray!10}66\% (15-86\%)&\cellcolor{gray!10}97\% (90-99\%)\\
\hline
\end{tabular}
\end{table}

