\begin{table}[!ht]
\caption{Protection due to various combinations of past infection preceding vaccination {\it against hospitalization} for the {\it Omicron} and the {\it Delta} variant of the SARS-CoV-2 virus, 95\% confidence intervals (CI) in parentheses. The inverse immunisation order: more than 2 months old full vaccination followed by infection in recent 6 months had protection 94\% (78-99\%) for the Omicron variant and 100\% (\nocase) for the Delta variant.}
\vspace{2mm}
\label{tabHinteractions}
\centering
\begin{tabular}{|C{.1\linewidth}|C{.16\linewidth}|C{.16\linewidth}|C{.16\linewidth}|C{.16\linewidth}|}
\hline
 \cellcolor{gray!20}$o$ {\it Hosp}&\cellcolor{gray!20}Booster 2-&\cellcolor{gray!20}Full 2-&\cellcolor{gray!20}Booster 2+&\cellcolor{gray!20}Full 2+\\
\hline
\cellcolor{gray!20}& 100\% & 100\% & 71\% & 93\% \\
\multirow{-2}{*}{\cellcolor{gray!20}Inf 6-}
&\nocase&\nocase&(0-96\%)&(49-99\%)\\
\hline
\cellcolor{gray!20}&95\%&94\%&90\%&73\%\\
\multirow{-2}{*}{\cellcolor{gray!20}Inf 6+}&(78-99\%)&(77-95\%)&(64-98\%)&(78-99\%)\\
\hline
\hline
\cellcolor{gray!20}$\delta$ {\it Hosp}&\cellcolor{gray!20}Booster 2-&\cellcolor{gray!20}Full 2-&\cellcolor{gray!20}Booster 2+&\cellcolor{gray!20}Full 2+\\
\hline
\cellcolor{gray!20}& 100\% & 100\% & 100\%  & 100\%  \\
\multirow{-2}{*}{\cellcolor{gray!20}Inf 6-}
&\nocase&\nocase&\nocase&\nocase\\
\hline
\cellcolor{gray!20}& 99\% & 97\%  & 98\%  & 98\%  \\
\multirow{-2}{*}{\cellcolor{gray!20}Inf 6+}&(99-100\%)&(91-99\%)&(85-100\%)&(98-100\%)\\
\hline
\end{tabular} \\[0.5ex]
\end{table}

