\begin{table}[!ht]
\caption{Protection due to various combinations of past infection preceding vaccination  {\it against infection} for the {\it Omicron} and the {\it Delta} variants of the SARS-CoV-2 virus.  Infection in recent 6 months is denoted as Inf 6- and older Inf 6+, completed vaccination scheme is denoted Full 2- for completion in recent 2 months and Full 2+ for older completion, analogously for booster. In parentheses, 95\% confidence intervals (CI) are given. The inverse immunisation order had a higher effect for the Omicron variant: more than 2 months old full vaccination followed by infection in recent 6 months gives 89\% (88-91\%). For the Delta variant, the value is comparable 96\% (90-98\%).}
\vspace{2mm}
\label{tabIinteractions}
\centering
\begin{tabular}{|C{.1\linewidth}|C{.16\linewidth}|C{.16\linewidth}|C{.16\linewidth}|C{.16\linewidth}|}
\hline
\cellcolor{gray!20}$o$ {\it Inf.}&\cellcolor{gray!20}Booster 2- & \cellcolor{gray!20}Full 2-&\cellcolor{gray!20}Booster 2+& \cellcolor{gray!20}Full 2+\\
\hline
\cellcolor{gray!20}&92\%&82\%&82\%&86\% \\
 \multirow{-2}{*}{\cellcolor{gray!20}Inf 6-}&(89-94\%)& (75-87\%)&(72-89\%)&(85-88\%)\\
\hline
\cellcolor{gray!20}&74\%&77\%&48\%&45\%\\
 \multirow{-2}{*}{\cellcolor{gray!20}Inf 6+}&(73-75\%)&  (76-78\%) &(45-52\%)&(44-46\%)\\
\hline \hline
\cellcolor{gray!20}$\delta$ {\it Inf.}&\cellcolor{gray!20}Booster 2-&\cellcolor{gray!20}Full 2-&\cellcolor{gray!20}Booster 2+ &\cellcolor{gray!20}Full 2+\\
\hline
\cellcolor{gray!20}&95\%&100\%&100\%&97\%\\
 \multirow{-2}{*}{\cellcolor{gray!20} Inf 6-}&(66-99\%)& \nocase&\nocase&(94-98\%)\\
\hline
\cellcolor{gray!20}&98\%&98\%&94\%&96\%\\ \multirow{-2}{*}{\cellcolor{gray!20}Inf 6+}&(98-99\%)&(97-98\%)&(89-97\%)&(95-96\%)\\
\hline
\end{tabular}
\end{table}




